#!/usr/bin/env bash
INIT_LOCK="_asite_lock"
APT_UPDATE="apt-get update"
APT_INSTALL="apt-get install"
_MY_CONF="my.cnf"
_INIT_DB="init.db"
MY_CONF="/etc/mysql/my.cnf"
INIT_MYSQL="/etc/init.d/mysql"
TOMCAT="tomcat7"
INIT_TOMCAT="/etc/init.d/$TOMCAT"
CATALINA_SH="/usr/share/$TOMCAT/bin/catalina.sh"