/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package tbase;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;
import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({ "cast", "rawtypes", "serial", "unchecked" })
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-12-20")
public class TMapSI implements org.apache.thrift.TBase<TMapSI, TMapSI._Fields>, java.io.Serializable, Cloneable, Comparable<TMapSI> {

    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TMapSI");

    private static final org.apache.thrift.protocol.TField TMAP_FIELD_DESC = new org.apache.thrift.protocol.TField("tmap", org.apache.thrift.protocol.TType.MAP, (short) 1);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();

    // required
    protected Map<String, Integer> tmap;

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;

    static {
        schemes.put(StandardScheme.class, new TMapSIStandardSchemeFactory());
        schemes.put(TupleScheme.class, new TMapSITupleSchemeFactory());
    }

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {

        TMAP((short) 1, "tmap");

        private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

        static {
            for (_Fields field : EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
        public static _Fields findByThriftId(int fieldId) {
            switch(fieldId) {
                case // TMAP
                1:
                    return TMAP;
                default:
                    return null;
            }
        }

        /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
        public static _Fields findByThriftIdOrThrow(int fieldId) {
            _Fields fields = findByThriftId(fieldId);
            if (fields == null)
                throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
            return fields;
        }

        /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
        public static _Fields findByName(String name) {
            return byName.get(name);
        }

        private final short _thriftId;

        private final String _fieldName;

        _Fields(short thriftId, String fieldName) {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        public short getThriftFieldId() {
            return _thriftId;
        }

        public String getFieldName() {
            return _fieldName;
        }
    }

    static {
        Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
        tmpMap.put(_Fields.TMAP, new org.apache.thrift.meta_data.FieldMetaData("tmap", org.apache.thrift.TFieldRequirementType.DEFAULT, new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32))));
        metaDataMap = Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TMapSI.class, metaDataMap);
    }

    public TMapSI() {
    }

    public TMapSI(Map<String, Integer> tmap) {
        this();
        this.tmap = tmap;
    }

    /**
   * Performs a deep copy on <i>other</i>.
   */
    public TMapSI(TMapSI other) {
        if (other.isSetTmap()) {
            Map<String, Integer> __this__tmap = new HashMap<String, Integer>(other.tmap);
            this.tmap = __this__tmap;
        }
    }

    public TMapSI deepCopy() {
        return new TMapSI(this);
    }

    @Override
    public void clear() {
        this.tmap = null;
    }

    public int getTmapSize() {
        return (this.tmap == null) ? 0 : this.tmap.size();
    }

    public void putToTmap(String key, int val) {
        if (this.tmap == null) {
            this.tmap = new HashMap<String, Integer>();
        }
        this.tmap.put(key, val);
    }

    public Map<String, Integer> getTmap() {
        return this.tmap;
    }

    public TMapSI setTmap(Map<String, Integer> tmap) {
        this.tmap = tmap;
        return this;
    }

    public void unsetTmap() {
        this.tmap = null;
    }

    /** Returns true if field tmap is set (has been assigned a value) and false otherwise */
    public boolean isSetTmap() {
        return this.tmap != null;
    }

    public void setTmapIsSet(boolean value) {
        if (!value) {
            this.tmap = null;
        }
    }

    public void setFieldValue(_Fields field, Object value) {
        switch(field) {
            case TMAP:
                if (value == null) {
                    unsetTmap();
                } else {
                    setTmap((Map<String, Integer>) value);
                }
                break;
        }
    }

    public Object getFieldValue(_Fields field) {
        switch(field) {
            case TMAP:
                return getTmap();
        }
        throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
        if (field == null) {
            throw new IllegalArgumentException();
        }
        switch(field) {
            case TMAP:
                return isSetTmap();
        }
        throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
        if (that == null)
            return false;
        if (that instanceof TMapSI)
            return this.equals((TMapSI) that);
        return false;
    }

    public boolean equals(TMapSI that) {
        if (that == null)
            return false;
        boolean this_present_tmap = true && this.isSetTmap();
        boolean that_present_tmap = true && that.isSetTmap();
        if (this_present_tmap || that_present_tmap) {
            if (!(this_present_tmap && that_present_tmap))
                return false;
            if (!this.tmap.equals(that.tmap))
                return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        List<Object> list = new ArrayList<Object>();
        boolean present_tmap = true && (isSetTmap());
        list.add(present_tmap);
        if (present_tmap)
            list.add(tmap);
        return list.hashCode();
    }

    @Override
    public int compareTo(TMapSI other) {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }
        int lastComparison = 0;
        lastComparison = Boolean.valueOf(isSetTmap()).compareTo(other.isSetTmap());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetTmap()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tmap, other.tmap);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    public _Fields fieldForId(int fieldId) {
        return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
        schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
        schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TMapSI(");
        boolean first = true;
        sb.append("tmap:");
        if (this.tmap == null) {
            sb.append("null");
        } else {
            sb.append(this.tmap);
        }
        first = false;
        sb.append(")");
        return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
        try {
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private static class TMapSIStandardSchemeFactory implements SchemeFactory {

        public TMapSIStandardScheme getScheme() {
            return new TMapSIStandardScheme();
        }
    }

    private static class TMapSIStandardScheme extends StandardScheme<TMapSI> {

        public void read(org.apache.thrift.protocol.TProtocol iprot, TMapSI struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true) {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch(schemeField.id) {
                    case // TMAP
                    1:
                        if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
                            {
                                org.apache.thrift.protocol.TMap _map10 = iprot.readMapBegin();
                                struct.tmap = new HashMap<String, Integer>(2 * _map10.size);
                                String _key11;
                                int _val12;
                                for (int _i13 = 0; _i13 < _map10.size; ++_i13) {
                                    _key11 = iprot.readString();
                                    _val12 = iprot.readI32();
                                    struct.tmap.put(_key11, _val12);
                                }
                                iprot.readMapEnd();
                            }
                            struct.setTmapIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();
            // check for required fields of primitive type, which can't be checked in the validate method
            struct.validate();
        }

        public void write(org.apache.thrift.protocol.TProtocol oprot, TMapSI struct) throws org.apache.thrift.TException {
            struct.validate();
            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.tmap != null) {
                oprot.writeFieldBegin(TMAP_FIELD_DESC);
                {
                    oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.I32, struct.tmap.size()));
                    for (Map.Entry<String, Integer> _iter14 : struct.tmap.entrySet()) {
                        oprot.writeString(_iter14.getKey());
                        oprot.writeI32(_iter14.getValue());
                    }
                    oprot.writeMapEnd();
                }
                oprot.writeFieldEnd();
            }
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }
    }

    private static class TMapSITupleSchemeFactory implements SchemeFactory {

        public TMapSITupleScheme getScheme() {
            return new TMapSITupleScheme();
        }
    }

    private static class TMapSITupleScheme extends TupleScheme<TMapSI> {

        @Override
        public void write(org.apache.thrift.protocol.TProtocol prot, TMapSI struct) throws org.apache.thrift.TException {
            TTupleProtocol oprot = (TTupleProtocol) prot;
            BitSet optionals = new BitSet();
            if (struct.isSetTmap()) {
                optionals.set(0);
            }
            oprot.writeBitSet(optionals, 1);
            if (struct.isSetTmap()) {
                {
                    oprot.writeI32(struct.tmap.size());
                    for (Map.Entry<String, Integer> _iter15 : struct.tmap.entrySet()) {
                        oprot.writeString(_iter15.getKey());
                        oprot.writeI32(_iter15.getValue());
                    }
                }
            }
        }

        @Override
        public void read(org.apache.thrift.protocol.TProtocol prot, TMapSI struct) throws org.apache.thrift.TException {
            TTupleProtocol iprot = (TTupleProtocol) prot;
            BitSet incoming = iprot.readBitSet(1);
            if (incoming.get(0)) {
                {
                    org.apache.thrift.protocol.TMap _map16 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.I32, iprot.readI32());
                    struct.tmap = new HashMap<String, Integer>(2 * _map16.size);
                    String _key17;
                    int _val18;
                    for (int _i19 = 0; _i19 < _map16.size; ++_i19) {
                        _key17 = iprot.readString();
                        _val18 = iprot.readI32();
                        struct.tmap.put(_key17, _val18);
                    }
                }
                struct.setTmapIsSet(true);
            }
        }
    }

    public TMapSI create() {
        return new TMapSI();
    }

    public TMapSI clone() {
        return cloneDepth(0);
    }

    public TMapSI cloneDepth(int _depth) {
        TMapSI _clone = create();
        _clone.tmap = tmap;
        cloneMore(_clone, _depth);
        return _clone;
    }

    public void cloneMore(TMapSI _clone, int _depth) {
    }
}
